# Generated by Django 3.2.5 on 2021-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
