# Generated by Django 3.2.5 on 2021-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photky', '0002_auto_20210803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails'),
        ),
    ]
