# Generated by Django 3.2.5 on 2021-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photky', '0004_alter_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbnails'),
        ),
    ]
